# Site settings
#title: Another Blog
title: Luel Hagos
url: "http://luelhagos.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  Welcome to my personal blog. Enjoy!!

# Your information
#email: 
author: Luel Hagos
avatar: "https://github.com/luelhagos/luelhagos.github.io/blob/gh-pages/Photos/luel_pc.jpeg?raw=true"
profile: Data Scientist 
#twitter_username: 
#github_username:  
profile_links:
  #Email: ""
  GitHub: " https://github.com/luelhagos"
  LinkedIn: "https://www.linkedin.com/in/luel-hagos"
  #Twitter: ""
  #CV: ""
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: luel   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

#navbar-links:
header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    HOME: /
    PROJECTS: /projects/
    ABOUT ME: /about/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
